#define GRANTLEE_VERSION_MAJOR @Grantlee5_VERSION_MAJOR@
#define GRANTLEE_VERSION_MINOR @Grantlee5_VERSION_MINOR@
#define GRANTLEE_VERSION_PATCH @Grantlee5_VERSION_PATCH@
#define GRANTLEE_VERSION_STRING "@Grantlee5_VERSION_STRING@"
#define GRANTLEE_MAJOR_MINOR_VERSION_STRING "@Grantlee5_MAJOR_MINOR_VERSION_STRING@"
#define GRANTLEE_MIN_PLUGIN_VERSION @Grantlee5_MIN_PLUGIN_VERSION@
