#define GRANTLEE_VERSION_MAJOR @Grantlee_VERSION_MAJOR@
#define GRANTLEE_VERSION_MINOR @Grantlee_VERSION_MINOR@
#define GRANTLEE_VERSION_PATCH @Grantlee_VERSION_PATCH@
#define GRANTLEE_VERSION_STRING "@Grantlee_VERSION_STRING@"
#define GRANTLEE_MAJOR_MINOR_VERSION_STRING "@Grantlee_MAJOR_MINOR_VERSION_STRING@"
#define GRANTLEE_MIN_PLUGIN_VERSION @Grantlee_MIN_PLUGIN_VERSION@
