#define GRANTLEE_VERSION_MAJOR @GRANTLEE_VERSION_MAJOR@
#define GRANTLEE_VERSION_MINOR @GRANTLEE_VERSION_MINOR@
#define GRANTLEE_VERSION_PATCH @GRANTLEE_VERSION_PATCH@
#define GRANTLEE_VERSION_STRING "@GRANTLEE_VERSION_STRING@"
#define GRANTLEE_MAJOR_MINOR_VERSION_STRING "@GRANTLEE_MAJOR_MINOR_VERSION_STRING@"
#define GRANTLEE_MIN_PLUGIN_VERSION @GRANTLEE_MIN_PLUGIN_VERSION@

