#!/bin/bash

# apply kdepim coding style to all c, cpp and header files in and below the current directory 
# 
# requirements: installed astyle 

astyle --indent=spaces=2 --brackets=linux \
      --indent-labels --pad=oper --pad=paren-in --unpad=paren \
      --one-line=keep-statements --convert-tabs \
      --indent-preprocessor \
      `find -type f -name '*.c'` `find -type f -name '*.cpp'` `find -type f -name '*.h'`
