# - Find cccc
#
# CCCC_EXECUTABLE - the cccc binary


INCLUDE(FindPackageHandleStandardArgs)

FIND_PROGRAM(CCCC_EXECUTABLE cccc)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(Cccc DEFAULT_MSG CCCC_EXECUTABLE)

MARK_AS_ADVANCED(CCCC_EXECUTABLE)
