# - Find lcov
#
# LCOV_EXECUTABLE - the lcov binary
# GENHTML_EXECUTABLE - the genhtml executable
#

INCLUDE(FindPackageHandleStandardArgs)

FIND_PROGRAM(LCOV_EXECUTABLE lcov)
FIND_PROGRAM(GENHTML_EXECUTABLE genhtml)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(LCov DEFAULT_MSG LCOV_EXECUTABLE GENHTML_EXECUTABLE)

MARK_AS_ADVANCED(LCOV_EXECUTABLE GENHTML_EXECUTABLE)
